var imgHeight = 0;
var imgWidth = 0; 
var w,h,f;
/*document.getElementById('submit_form_details').addEventListener('click',
    function() {
        console.log('Success valid !!');
        var node = document.getElementById('contact_form_main_node');
            domtoimage.toPng(node)
            .then(function(dataUrl) {
                console.log(dataUrl);
                window.open(dataUrl);
                var img = new Image();
                img.src = dataUrl;
                var file= dataURLtoBlob(dataUrl);
                var fd1 = new FormData();
                fd1.append("uploadimgleft-main", file);
        //document.getElementById("here-appear-theimages").appendChild(img);
            })
            .catch(function(error) {
                console.error('oops, something went wrong!', error);
            });
        });*/

$(document).ready(function(){
	$("#image").change(function(){
        readImageData(this);
        $(".preview_box").removeClass("imgMode");
    });

    $("#btnCreate").click(function() { 
        var node = document.getElementById('preview_box');
        var image = document.getElementById('mainImg');

        domtoimage.toPng(node).then(function (pngDataUrl) {
            image.src = pngDataUrl;
        });
    }); 

    $("#btnSave").click(function() { 
        /*var url = $("#mainImg")[0].src.replace(/^data:image\/[^;]+/, 'data:application/octet-stream');
        window.open(url);*/
        saveImage($("#mainImg")[0].src);
        /*var img = $("#mainImg")[0];
        // atob to base64_decode the data-URI
        var image_data = atob(img.src.split(',')[1]);
        // Use typed arrays to convert the binary data to a Blob
        var arraybuffer = new ArrayBuffer(image_data.length);
        var view = new Uint8Array(arraybuffer);
        for (var i=0; i<image_data.length; i++) {
            view[i] = image_data.charCodeAt(i) & 0xff;
        }
        try {
            // This is the recommended method:
            var blob = new Blob([arraybuffer], {type: 'application/octet-stream'});
        } catch (e) {
            // The BlobBuilder API has been deprecated in favour of Blob, but older
            // browsers don't know about the Blob constructor
            // IE10 also supports BlobBuilder, but since the `Blob` constructor
            //  also works, there's no need to add `MSBlobBuilder`.
            var bb = new (window.WebKitBlobBuilder || window.MozBlobBuilder);
            bb.append(arraybuffer);
            var blob = bb.getBlob('application/octet-stream'); // <-- Here's the Blob
        }

        // Use the URL object to create a temporary URL
        var url = (window.webkitURL || window.URL).createObjectURL(blob);
        location.href = url;*/

        /*var fs = require('fs');
        // string generated by canvas.toDataURL()
        var img = $("#mainImg")[0].src;
        // strip off the data: url prefix to get just the base64-encoded bytes
        var data = img.replace(/^data:image\/\w+;base64,/, "");
        var buf = new Buffer(data, 'base64');
        fs.writeFile('image.png', buf);*/
    }); 

    $(".btnPortrait").click(function(){
        $(".preview_box").addClass("imgMode");
        if($(this).attr("initialMode")=="true"){
            $(".preview_box").removeClass("imgMode");
        }
    	$(".btnMode").removeClass("active");
    	$(this).addClass("active");
        $(".preview_box").removeClass("portrait landscape square").addClass("portrait");
    });

    $(".btnLandscape").click(function(){
        $(".preview_box").addClass("imgMode");
        if($(this).attr("initialMode")=="true"){
            $(".preview_box").removeClass("imgMode");
        }
    	$(".btnMode").removeClass("active");
    	$(this).addClass("active");
        $(".preview_box").removeClass("portrait landscape square").addClass("landscape");
    });

    $(".btnSquare").click(function(){
        $(".preview_box").addClass("imgMode");
        if($(this).attr("initialMode")=="true"){
            $(".preview_box").removeClass("imgMode");
        }
    	$(".btnMode").removeClass("active");
    	$(this).addClass("active");
        $(".preview_box").removeClass("portrait landscape square").addClass("square");
    });

    addLeftSideBoxClick();
});

function readImageData(imgData){
	if (imgData.files && imgData.files[0]) {
        var readerObj = new FileReader();
        
        readerObj.onload = function (element) {
            $('#preview_img').attr('src', element.target.result);
        }

        readerObj.readAsDataURL(imgData.files[0]);
        
        $(".imageloader").removeClass("displaynone");
        $("#preview_img").addClass("displaynone");
        
        setTimeout(function(){ 
        	checkOrientation();
        	$(".imageloader").addClass("displaynone");
        	$("#preview_img").removeClass("displaynone");
        	$(".products").removeClass("displaynone");
        	/*$(".products .product").click(function(){
        		if($(this).hasClass("product-overcast")){
                    alert("image is small");
                }else{
                    $(".products .product").removeClass("selected");
                    $(this).addClass("selected");    
                }
        	})*/

        }, 1000);
	}
}

function checkOrientation(){
	//var imgHeight = $("#preview_img").height();
    //var imgWidth = $("#preview_img").width();
    imgHeight = $("#preview_img")[0].naturalHeight;
    imgWidth = $("#preview_img")[0].naturalWidth;
    console.log(imgHeight + " " + imgWidth)
    if(imgHeight > imgWidth){
    	setImageDimention("portrait");
    }else if(imgHeight < imgWidth){
    	setImageDimention("landscape");
    }else{
    	setImageDimention("square");
    }
}

function setImageDimention(mode){
	$(".btnMode").removeClass("active");
    if(mode == "portrait"){
		$(".btnPortrait").addClass("active");
        $(".btnMode").attr("initialMode","false");
        $(".btnPortrait").attr("initialMode","true");
        $(".preview_box").removeClass("portrait landscape square").addClass("portrait");
		$(".products .product .box").each(function(){
			var boxHeight = $(this).attr("bxHeight");
			var boxWidth = $(this).attr("bxWidth");
			$(this).css("height",boxHeight*4);
			$(this).css("width",boxWidth*4);
		});
        selectLeftSideBox("portrait");
	}else if(mode == "landscape"){
		$(".btnLandscape").addClass("active");
        $(".btnMode").attr("initialMode","false");
        $(".btnLandscape").attr("initialMode","true");
        $(".preview_box").removeClass("portrait landscape square").addClass("landscape");
		$(".products .product").each(function(){
			var boxHeight = $(this).find(".box").attr("bxHeight");
			var boxWidth = $(this).find(".box").attr("bxWidth");
			$(this).find(".box").css("height",boxWidth*4);
			$(this).find(".box").css("width",boxHeight*4);
		});
        selectLeftSideBox("landscape");
	}else{
		$(".btnSquare").addClass("active");
        $(".btnMode").attr("initialMode","false");
        $(".btnSquare").attr("initialMode","true");
        $(".preview_box").removeClass("portrait landscape square").addClass("square");
		$(".products .product").each(function(){
			var boxWidth = $(this).find(".box").attr("bxWidth");
			$(this).find(".box").css("height",boxWidth*4);
			$(this).find(".box").css("width",boxWidth*4);
		});
        selectLeftSideBox("square");
	}
}

function selectLeftSideBox(imgMode){
    if(imgMode == "portrait"){
        activeDeactiveLeftSideBox(imgHeight,imgMode);            
    }else if(imgMode == "landscape"){
        activeDeactiveLeftSideBox(imgWidth,imgMode);
    }else{
        activeDeactiveLeftSideBox(imgHeight,imgMode);
    }    
}

function activeDeactiveLeftSideBox(dimention,imgMode){
    $(".products .product").removeClass("selected product-overcast");
    if(dimention > 1500 ){
        console.log("Extra Large");
        //$(".products .product").removeClass("selected");
        $("[boxsize='extralarge']").addClass("selected");
    }else if (dimention > 1200) {
        console.log("Large");
        //$(".products .product").removeClass("selected");
        $("[boxsize='large']").addClass("selected");
        $("[boxsize='extralarge']").addClass("product-overcast");
    }else if (dimention > 900) {
        console.log("Classic");
        //$(".products .product").removeClass("selected");
        $("[boxsize='classic']").addClass("selected");
        $("[boxsize='large']").addClass("product-overcast");
        $("[boxsize='extralarge']").addClass("product-overcast");
    }else if (dimention > 600) {
        console.log("Medium");
        //$(".products .product").removeClass("selected");
        $("[boxsize='medium']").addClass("selected");
        $("[boxsize='classic']").addClass("product-overcast");
        $("[boxsize='large']").addClass("product-overcast");
        $("[boxsize='extralarge']").addClass("product-overcast");
    }else if (dimention > 300) {
        console.log("Small");
        //$(".products .product").removeClass("selected");
        $("[boxsize='small']").addClass("selected");
        $("[boxsize='medium']").addClass("product-overcast");
        $("[boxsize='classic']").addClass("product-overcast");
        $("[boxsize='large']").addClass("product-overcast");
        $("[boxsize='extralarge']").addClass("product-overcast");
    }
    
    setTimeout(function(){
        $(".preview_box").css("width","");
        $(".preview_box").css("height","");
        
        /*if(imgMode == "portrait"){
            

            $(".preview_box").css("width", + 6);
            $(".preview_box").css("height",$("#preview_img").height() + 6);
        }else if(imgMode == "landscape"){
            $(".preview_box").css("width",$("#preview_img").width() + 6);
            $(".preview_box").css("height",$("#preview_img").height() + 6);
        }else{
            $(".preview_box").css("width",$("#preview_img").width() + 6);
            $(".preview_box").css("height",$("#preview_img").height() + 6);
        } */
    },100);
}

function addLeftSideBoxClick(){
    $(".products .product").click(function(){
        if($(this).hasClass("product-overcast")){
            alert("image is small");
        }else{
            $(".products .product").removeClass("selected");
            $(this).addClass("selected");    
        }
    });
}

function saveImage(base64string) {
    var imageData = base64string.split(',')[1];
    var a = $("<a>").attr("href", "data:Application/base64," + imageData )
                    .attr("download","image.png")
                    .appendTo("body");

        a[0].click();

    a.remove();
}